### ISSUE TITLE
bug: npm bundle is invalid with version 1.35.0

### ISSUE THREAD

**Issue by favna** [LongTengDao/j-toml#22]
The top most line in the `index.d.ts` file of the npm bundle is invalid as of version 1.35.0:

https://github.com/LongTengDao/j-toml/blob/4704c32d6fcff1db2497a98375117de585ea323b/dist/NPM/index.d.ts#L1

![image](https://user-images.githubusercontent.com/4019718/188234439-7af08e84-4337-4027-86b4-c9e2cc6fba07.png)

Reverting to `~1.33.0` fixes it for now.

I diffed the 2 versions and the reason is you added:
```ts
	export class Keys extends RegExp {
	readonly lastIndex :number;
	constructor (keys :ArrayLike<string>);
	readonly test :(this :Keys, key :string) => boolean;
}
```
See diff here: https://www.diffchecker.com/3Ra291yt

TypeScript doesn't allow mixing `export = ` with other top level exports.

**Comment by LongTengDao** [comment]
Nice catch.

Fixed in v1.35.1

**Comment by favna** [comment]
Sorry to say but it's not fixed entirely just yet:

![image](https://user-images.githubusercontent.com/4019718/188265236-46e2b46e-e50d-41f4-b1f2-8b886cae0515.png)

You should add `declare` in front of the class still.

**Comment by LongTengDao** [comment]
Oh... @favna thank you, now it's fixed... (v1.35.2)
